version: '3.8'

services:
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-init-eis
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:2003@host.docker.internal:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iot-network

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver-eis
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: api-server
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:2003@host.docker.internal:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_WWW_USER_USERNAME: admin
      AIRFLOW_WWW_USER_PASSWORD: admin
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: eis_db
      DB_USER: postgres
      DB_PASSWORD: 2003
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iot-network
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler-eis
    depends_on:
      - airflow-webserver
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:2003@host.docker.internal:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: eis_db
      DB_USER: postgres
      DB_PASSWORD: 2003
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    external: true
    name: rt360_network
