FROM apache/airflow:3.0.6

USER root

USER airflow

COPY requirements-airflow.txt /requirements-airflow.txt

ARG AIRFLOW_VERSION=3.0.6
ARG PYTHON_VERSION=3.12
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN pip install --no-cache-dir --constraint "${CONSTRAINT_URL}" -r /requirements-airflow.txt
